Pull request number four - Desktop version update
ReshyResh/Portfolio pull request #4
Opened 2021-07-15 14:43 UTC by ReshyResh

# Requirements fulfilled succesfully 
 - Made sure no linter errors are present.
 - Used correct Github flow.
 - Used media queries to lay out the desktop version of the portfolio (Figma template n.5, which you can view [here](https://i.imgur.com/hq8W8Jr.jpg).
 - Implemented animated buttons and transitions for better UX.
 - Edited images and backgrounds to fit in the dark theme of the portfolio.
 

# Live Demo
You can see the website in action by clicking *[here](https://reshyresh.github.io/Portfolio/)*

# Screenshots and videos of functionalities
    - Interactable projects sessions, each with their dedicated hover function
    
![0cGIeDj](https://user-images.githubusercontent.com/85108160/125806709-ad37a280-ce78-4377-b00a-a37eddfe2f92.gif)

    - Animated buttons 
![eSCmXC9](https://user-images.githubusercontent.com/85108160/125807041-0b8d4684-4b79-408a-a28c-1f15f9ca20da.gif)

    - Working form 
![MQfikEX](https://user-images.githubusercontent.com/85108160/125807208-60c767f4-8808-4233-a507-b775768e0de6.gif)

2021-07-15 16:58 UTC, ZawadiSumba66 requested changes
#### Hi @ReshyResh 👋 , 

Good job so far!
However, are some issues that you still need to work on to go to the next project but you are almost there! 💪 

## Required Changes ♻️
Please ensure that you replicate the desktop version of Figma design as much as possible by using the media queries. Currently, the design on your desktop version is as similar as your mobile version. Let's fix this 👍 
_Check the comments under the review._

## Optional suggestions
_N/A_
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-15 16:58 UTC, ZawadiSumba66 commented on index.html
> +        </div><div class="shape-2"></div>
- [ ] In the regular projects(below the project title and the featured project) there should be an image aligned to the left of the page with no margin.
- [ ] There is also a second project that shares the first one's row but is bigger in height (taking also part of the next row also) and looks just like the featured project but the description is above the picture; takes about 25% of the page's width and is aligned completely to the right with no margin in the page.
- [ ] The third project is just a mockup image (like the first one) and is below the first project with no margin on top or left, this one takes 50% of the page's width.
- [ ] Lastly, there's a fourth project below the third one but starts in the center of the page and it takes about 30% of the page's width.
- [ ] Make sure to also add the necessary background designs as well.
All these is similar to the screenshot below.
![image](https://user-images.githubusercontent.com/68167810/125823121-a60399e9-ceb3-4615-b1c4-4593ea85ab3d.png)

2021-07-15 16:58 UTC, ZawadiSumba66 commented on index.html
> +    <div class="container container-middle">
- [ ] Let's also adjust the about section part to make a similar design as the one given.
If you look carefully, the skills, frameworks are aligned to the left, and the about part is to the right of it.
- [ ] On the left, there are two rows and two columns, the first row holds Languages and Frameworks respectively, and the second one the Skills.
- [ ] Make sure that you change the about title font to match the one on the template. 👇 
- [ ] The About section also has a white background also.
![image](https://user-images.githubusercontent.com/68167810/125823743-7c6257e7-5eca-4c46-a240-6c9a0bf4230d.png)

2021-07-15 16:58 UTC, ZawadiSumba66 commented on index.html
> +        <textarea name="message" maxlength="500" class="text-form text-form2" required placeholder="Enter your message here.."></textarea>
- [ ] The background color of this section should be `#F9F9FA`. 
- [ ] The name and email input text share the same row.
- [ ] The message input occupies the length of the name and email input.
- [ ] The `Get my CV` button should be placed in the same row as the social media icon links and aligned to the right and the social media icon links to the right.
- [ ] Make sure to also add the other background designs missing.
![image](https://user-images.githubusercontent.com/68167810/125826023-49121e52-380d-4e2b-a8d9-8dcee7787fb5.png)

2021-07-16 07:34 UTC, mikenath223 approved these changes
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-16 07:41 UTC, merged